version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: mimic_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=mimic_database
      - POSTGRES_USER=mimic_user
      - POSTGRES_PASSWORD=root
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: